# No new line at startup
add_newline = false

[character]
symbol = "âœ"
error_symbol = "âœ—"
use_symbol_for_status = true
disabled = false

prompt_order = [ "username", "hostname", "kubernetes", "directory", "git_branch", "git_commit", "git_state", "git_status", "hg_branch", "docker_context", "package", "dotnet", "elixir", "elm", "erlang", "golang", "haskell", "java", "julia", "nodejs", "php", "python", "ruby", "rust", "terraform", "nix_shell", "conda", "memory_usage", "aws", "env_var", "crystal", "cmd_duration", "custom", "line_break", "jobs", "battery", "time", "character", ]

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"
threshold = 98
disabled = false

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 50
style = "bold magenta"

[[battery.display]]
threshold = 70
style = "bold blue"
    
[[battery.display]]
threshold = 98
style = "bold pink"
  
 
[cmd_duration]
min_time = 500
prefix = "underwent "
 
[directory]
truncation_length = 3
truncate_to_repo = true
prefix = "in "
style = "bold cyan"
disabled = false
use_logical_path = true
 
[git_branch]
symbol = "ğŸŒ± "
truncation_length = "2^63 - 1"
truncation_symbol = "â€¦"
style = "bold purple"
disabled = false

[git_commit]
commit_hash_length = 6
prefix = "("
suffix = ")"
style = "bold green"
only_detached = false
disabled = false

[git_state]
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = "cherry_picking"
bisect = "bisecting"
am = "AM"
am_or_rebase = "AM/REBASE"
progress_divider = "/"
style = "bold yellow"
disabled = false

[git_status]
conflicted = "ğŸ³ "
ahead = "ğŸğŸ’¨ "
behind = "ğŸ˜° "
diverged = "ğŸ˜µ "
untracked = "ğŸ¤· "
stashed = "ğŸ“¦ "
modified = "ğŸ“ "
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "ğŸ‘… "
deleted = "ğŸ—‘ "

[hostname]
ssh_only = true
prefix = "âŸª"
suffix = "âŸ«"
trim_at = "."
disabled = false

[java]
symbol = "ğŸŒŸ "

[jobs]
symbol = "âœ¦"
threshold = 1
style = "bold blue"
disabled = false

[nodejs]
disabled = false
symbol = "ğŸ¤– "

[python]
pyenv_version_name = true
symbol = "î˜† "
disabled = false

[time]
format = "%a %e %h %R"
utc_time_offset = "local"
style = "bold purple"
disabled = false

[package]
symbol = "ï£– "
